# Server configurations
server.port=8080
server.servlet.context-path=/api

# Database connection details (Using PostgreSQL for Neon database integration)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/restaurantdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# Spring JPA / Hibernate preferences for PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

# Custom JWT Tokens Configuration parameters
jwt.secret=artisanfoodrestaurantappsupersecurelongsecrettokentoencryptjwtforcustomerandadminsessions
jwt.expirationMs=86400000
