# Server configurations
server.port=8080
server.servlet.context-path=/api

# Database connection details (Using H2 in-memory/file with autocommit and compatibility)
spring.datasource.url=jdbc:h2:mem:restaurantdb;DB_CLOSE_DELAY=-1;NON_KEYWORDS=KEY,VALUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Spring JPA / Hibernate preferences
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Custom JWT Tokens Configuration parameters
jwt.secret=artisanfoodrestaurantappsupersecurelongsecrettokentoencryptjwtforcustomerandadminsessions
jwt.expirationMs=86400000
